ДЗ 1
SofiaVolk/2020-1-Atom-QA-Python-S-Volkova pull request #1
Opened 2020-03-04 11:50 UTC by SofiaVolk

# Домашнее задание № 1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
*
*
*

2020-03-06 09:42 UTC, sniiick requested changes
Мелкие замечания.

+ всю домашку надо поместить в отдельную папку

2020-03-06 09:42 UTC, sniiick commented on test_int.py
> +    assert random.randint(0, 10000) != random.randint(0, 10000)
Плохой вариант. Вероятность одинакового рандома маленькая, но есть

2020-03-06 09:42 UTC, snicks92 commented on test_set.py
> +    @pytest.mark.parametrize('i', list(range(5)))
Нет разницы между параметрами для проверки, что add возвращает None

2020-03-06 09:42 UTC, snicks92 commented on test_str.py
> +        assert 'Hello, ' + 'world!' is not s
лучше !=

2020-03-06 19:34 UTC, sniiick requested changes

2020-03-06 19:34 UTC, snicks92 commented on hw1/test_str.py
> +        assert 'Hello, ' + 'world!' is not s
Все таки тут надо вместо is not сделать !=

2020-03-07 08:36 UTC, SofiaVolk commented on hw1/test_str.py
> +        assert 'Hello, ' + 'world!' is not s
изменила тест, теперь != вместо is not

2020-03-07 17:12 UTC, sniiick approved these changes

2020-03-07 17:12 UTC, merged